### ISSUE TITLE
Only show housenumbers

### ISSUE THREAD

**Issue by ThcDelux3** [PhilippTreupel/vuetify-here-geocoder-autocomplete#3]
First great work! Awesome tool.

My question. Is there a way to only show house numbers (not as the final result) but in the preview before you select?

for e.g 

Adress, Street 1
Adress, Street 2
Adress, Street 3
....

**Comment by PhilippTreupel** [comment]
Thanks for the feedback!
I am not quite sure if I have understood the question correctly...
If you want to show only results that contain a full address with house number, you need to set the property `result-type="houseNumber"` like this. But keep in mind that then a result will appear only after entering many letters because the results are filtered locally. In my tests, at least one number always had to be entered as well. So there is also no other option that allows to display all house numbers for a given street.

```html
<v-here-geocoder-autocomplete
   :here-api-key="hereApiKey"
   v-model="place"
   label="Search for any place..."
   debounce-time
   append-icon=""
   hide-no-data
   clearable
   outlined
   result-type="houseNumber"
 />
```

Unfortunately, there is currently no way to get only such data from the API. The feature may follow in the future. Then you could simply set the property `types=""` with the value then available for it. More information can be found [here](https://developer.here.com/documentation/geocoding-search-api/dev_guide/topics-api/code-autocomplete-result-type-filter.html).

If you want to display only the house number of an address in the results, you can achieve this via a custom highlight function: 
```vue
<template>
  <v-here-geocoder-autocomplete
     :here-api-key="hereApiKey"
     v-model="place"
     label="Search for any place..."
     debounce-time
     append-icon=""
     hide-no-data
     clearable
     outlined
     :custom-highlight="customHighlight"
   />
</template>
<script>
import VHereGeocoderAutocomplete from "./components/VHereGeocoderAutocomplete";

export default {
  components: {
    VHereGeocoderAutocomplete
  },
  data: () => ({
    hereApiKey: "your_api_key",
    place: null
  methods: {
   customHighlight(placeItem) {
      if (placeItem.address.houseNumber != null) {
        return placeItem.address.houseNumber;
      } else {
        return placeItem.title;
      }
    }
  }
};
</script>
```

However, it would probably be a bad user experience if only house numbers are displayed and the user does not know where they belong. Alternatively, you could use this function to highlight only the house numbers. 

I hope the information helps, otherwise you can describe your question again with an exact use case.
