### ISSUE TITLE
Nuxt | Navigator is not defined

### ISSUE THREAD

**Issue by ThcDelux3** [PhilippTreupel/vuetify-here-geocoder-autocomplete#4]
Hey,

basic install of nuxt (vuetify + axios). 

Error Message:

**ReferenceError**
navigator is not defined

Line 8447 of node_modules\vuetify-here-geocoder-autocomplete\dist\VHereGeocoderAutocomplete.common.js :
   
default: navigator.language ? navigator.language : null

Any Idea how to fix this? Where could I provide a default value like null?

Best Regards Felix.

**Comment by PhilippTreupel** [comment]
Hi,
the `navigator` object is a standard interface provided by the browser and widely supported by browsers. Info [here](https://developer.mozilla.org/en-US/docs/Web/API/Navigator). Via `navigator.language` the language set by the user is read from the browser and written to the `lang` parameter. You can read about the functionality of `lang` in the documentation. The code is only executed if you don't pass a value for the `lang` parameter. You can try if it works if you assign an appropriate value to `lang`. Since you didn't provide any other info about your implementation, I can't say exactly why the navigator object is not available. However, the code should not depend on the availability of the `navigator` object, I'll fix that with the next version in a few weeks (I hope you can wait until then).

**Comment by ThcDelux3** [comment]
Thanks for the super-fast response. A few weeks of waiting looks fine :) portig my app from basic Vue where everything works as expected to Nuxt.

Clean nuxt project (with my configuration) with the implementation of vuetify-here-geocoder-autocomplete to reproduce the error.

https://github.com/ThcDelux3/VuetifyHereGeocoderAutocomplete-Nuxt

I tried to define the lang with en, en-US, de-DE but it didn't fix the issue. :/ maybe you can find the issue.

**Comment by ThcDelux3** [comment]
Found the issuse for Navigator. When using SSR you need to create a plugin in the nuxt plugins folder an import it like this     {src: '~/plugins/vuetifyHereGeocoderAutocomplete.js', mode: 'client'}, in the nuxt config file

**Comment by ThcDelux3** [comment]
Now the component works but im getting [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

Will keep u updatet.
